### ISSUE TITLE
wizard : object wrapper missing into Tag.js ?

### ISSUE THREAD

**Issue by kendrick-k** [QubitProducts/OpenTag#8]
While generating a new tag on branch opentag-v3 with java -jar shared/bin/LibraryWizard.jar --wizard, 
"return {" instruction was missing from generated Tag.js. I had to add it manually, normal ?

qubit.opentag.LibraryTag.define("tagname.tagname.v1.Tag", {
	getDefaultConfig: function () {
		return {// missing
			/*DATA*/
			description: "DESCRIPTION.",
			name: "TAG_NAME",
...
		}//missing

**Comment by peterfronc** [comment]
This branch is unstable and in aplha state. Please use master branch.

**Comment by kendrick-k** [comment]
sure !
